neo4j_credentials:
  NEO4J_URI: bolt://172.25.0.3:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: Neo4JJJJJ
  NEO4J_DB: graphdb2

# neo4j_credentials:
#   NEO4J_URI: bolt://192.168.1.151:7687
#   NEO4J_USERNAME: neo4j
#   NEO4J_PASSWORD: password
#   NEO4J_DB: neo4j

MINIMUM_NUMBER_OF_SAMPLES_FOR_DISEASE_TO_BE_INCLUDED: 0